force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>LEAD-{00000}</displayFormat>
        <label>Lead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
public class LeadTriggerHandler {
    public static void afterInsert(List<Lead__c> LeadList){
        
        if(LeadList.size()>0 && !LeadList.isEmpty()){
            LeadHelper.createTATRecord(LeadList);
        }
    }
    
    public static void afterUpdate(List<Lead__c> LeadList,Map<Id,Lead__c> LeadOldMap){
		List<Lead__c> LeadListTAT = new List<Lead__c>();
        Map<Id,Lead__c> LeadOldMapTAT = new Map<Id,Lead__c>();
		for(Lead__c leadObj:LeadList){
            if(leadObj.Stage__c != null && (LeadOldMap.get(leadObj.Id).Stage__c != leadObj.Stage__c)){
                LeadListTAT.add(leadObj);
                LeadOldMapTAT.put(leadObj.Id,LeadOldMap.get(leadObj.Id));
            }           
        }        
        if(LeadListTAT.size()>0 && !LeadListTAT.isEmpty()){
            LeadHelper.stageChangeTATRecord(LeadListTAT,LeadOldMapTAT);
        }
    }
}