force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>LEAD-{00000}</displayFormat>
        <label>Lead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Turn_Around_Time__c/Turn_Around_Time__c.object-meta.xml
<CustomObject>
    <label>Turn Around Time</label>
    <nameField>
        <displayFormat>TAT-{000000}</displayFormat>
        <label>Turn Around Time Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Turn Around Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Turn_Around_Time__c/fields/Current_Stage__c.field-meta.xml
<CustomField>
    <fullName>Current_Stage__c</fullName>
    <label>Current Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Turn_Around_Time__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Turn Around Time</relationshipLabel>
    <relationshipName>Turn_Around_Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Turn_Around_Time__c/fields/Previous_Stage__c.field-meta.xml
<CustomField>
    <fullName>Previous_Stage__c</fullName>
    <label>Previous Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Turn_Around_Time__c/fields/Unique_String__c.field-meta.xml
<CustomField>
    <fullName>Unique_String__c</fullName>
    <label>Unique String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadHelper.cls
public class LeadHelper {
	public static void createTATRecord(List<Lead__c> LeadList){
        List<Turn_Around_Time__c> TATList = new List<Turn_Around_Time__c>();
        for(Lead__c leadObj:LeadList){
            Turn_Around_Time__c curTAT = new Turn_Around_Time__c();
			curTAT.Lead__c = leadObj.Id;  
			curTAT.Start_Date__c = System.Now();
			curTAT.Current_Stage__c = 'New';
            curTAT.Unique_String__c = 'New'+'-'+leadObj.Id;
			TATList.add(curTAT);            
        }
        
        if(TATList.size()>0 && !TATList.isEmpty()){
            Database.insert(TATList,false);
        }
    }
    
    public static void stageChangeTATRecord(List<Lead__c> LeadList,Map<Id,Lead__c> LeadOldMap){
        List<Turn_Around_Time__c> TATList = new List<Turn_Around_Time__c>();
        Set<String> TATUpdateRecords = new Set<String>();
        for(Id leadId:LeadOldMap.keyset()){
            Lead__c oldLead = LeadOldMap.get(leadId);
            String curTATString = oldLead.Stage__c+'-'+leadId;
            TATUpdateRecords.add(curTATString);
        }
        List<Turn_Around_Time__c> updateTATList = new List<Turn_Around_Time__c>();
        updateTATList = [Select id,Unique_String__c,End_Date__c from Turn_Around_Time__c 
						 where Unique_String__c in:TATUpdateRecords];
        if(updateTATList.size()>0 && !updateTATList.isEmpty()){
            for(Turn_Around_Time__c currentTATRecord:updateTATList){
                currentTATRecord.End_Date__c = System.Now();
                TATList.add(currentTATRecord);
            }
        }
        Set<Id> leadIds = new Map<Id,Lead__c>(LeadOldMap).keyset();
        for(Lead__c leadObj:LeadList){
            Turn_Around_Time__c curTAT = new Turn_Around_Time__c();
			curTAT.Lead__c = leadObj.Id;  
			curTAT.Start_Date__c = System.Now();
			curTAT.Current_Stage__c = LeadObj.Stage__c;
            curTAT.Previous_Stage__c = LeadOldMap.get(leadObj.Id).Stage__c;
            curTAT.Unique_String__c = LeadObj.Stage__c+'-'+leadObj.Id;
			TATList.add(curTAT);            
        }
        
        if(TATList.size()>0 && !TATList.isEmpty()){
            Database.upsert(TATList,false);
        }
    }
}